const data = {
    "code": 200,
    "msg": "성공하였습니다.",
    "result": {
        "mapListBanner": {
            "bannerList": [],
            "config": {
                "isLoop": true,
                "bannerExposureStartPoint": 3,
                "bannerExposureGapCount": 10
            }
        },
        "roomList": [
            {
                "seq": 51739996,
                "id": "687466b880b06135b191dcbe",
                "roomTypeName": "오피스텔",
                "randomLocation": {
                    "lat": 37.48727,
                    "lng": 127.013737
                },
                "complexName": "엘루크서초",
                "roomTitle": "신축 첫 입주, 풀옵션 하이엔드 오피스텔",
                "roomDesc": "중층, 28.05m², 관리비 확인 불가",
                "priceTypeName": "월세",
                "priceTitle": "1000/100",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/HuAIclew88BCPNPBj0MPt",
                    "https://d1774jszgerdmk.cloudfront.net/512/Rs2dbEFtHk6fPhfXbmowG",
                    "https://d1774jszgerdmk.cloudfront.net/512/SJLKubEFvrxGg1rm5TAdO",
                    "https://d1774jszgerdmk.cloudfront.net/512/0Rr4iFB0iXSDar8gfKUvR",
                    "https://d1774jszgerdmk.cloudfront.net/512/21wer0EVGSCvHgkovjsXB"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10194,
                "dongName": "서초동"
            },
            {
                "seq": 51385594,
                "id": "685a470daabf0e545ffb6fc6",
                "roomTypeName": "원룸",
                "randomLocation": {
                    "lat": 37.5104429667111,
                    "lng": 127.027669338094
                },
                "complexName": null,
                "roomTitle": "도배해드려요 논현역인근, 완전 넓은 풀옵션 원룸+베란다",
                "roomDesc": "2층, 27m², 관리비 7만",
                "priceTypeName": "월세",
                "priceTitle": "5000/65",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/4beLEcfcRdAnDEuBAHjUX",
                    "https://d1774jszgerdmk.cloudfront.net/512/Q2DZrv4fBM-zRsBqBY6Rf",
                    "https://d1774jszgerdmk.cloudfront.net/512/v6BI-CvrOc944LP2JGoW0",
                    "https://d1774jszgerdmk.cloudfront.net/512/h4GPDrkidWe7UUMJAESsP",
                    "https://d1774jszgerdmk.cloudfront.net/512/xYGQwkeHO8kATkrWogsj0"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10133,
                "dongName": "논현동"
            },
            {
                "seq": 51959616,
                "id": "688329f98dc9332fd551e099",
                "roomTypeName": "원룸 • 단기",
                "randomLocation": {
                    "lat": 37.5102407040683,
                    "lng": 127.026601774939
                },
                "complexName": null,
                "roomTitle": "o월세 가드결제가능o가성비 정말 잘나오는 인기만점 원룸 나왔습니다.",
                "roomDesc": "중층, 16.52m², 관리비 7만",
                "priceTypeName": "월세",
                "priceTitle": "50/50",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/trZAQlW1yfOqNmgCleKOF",
                    "https://d1774jszgerdmk.cloudfront.net/512/cg9iaggnMRUpjJv44N-jz",
                    "https://d1774jszgerdmk.cloudfront.net/512/rsCC7mnkJgDt0sOE7T-u2",
                    "https://d1774jszgerdmk.cloudfront.net/512/7aHahWx1jNksnLT6Yh32C",
                    "https://d1774jszgerdmk.cloudfront.net/512/5xd1dBVcDxdRyRUajgHv7"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10133,
                "dongName": "논현동"
            },
            {
                "seq": 52007484,
                "id": "6887a90fa3610542468236c6",
                "roomTypeName": "원룸",
                "randomLocation": {
                    "lat": 37.5131399428402,
                    "lng": 127.018692495735
                },
                "complexName": null,
                "roomTitle": "신사역 도보 5분거리 논현역 도보 5분거리 저렴하게 나온 풀옵션 원룸",
                "roomDesc": "1층, 19.83m², 관리비 8만",
                "priceTypeName": "월세",
                "priceTitle": "500/47",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/IoVbiCRd85WMQxvaI8EvQ",
                    "https://d1774jszgerdmk.cloudfront.net/512/E0-joBprZd4Lyx1oO8GO5",
                    "https://d1774jszgerdmk.cloudfront.net/512/Iv8bf3-QphdXDdd1AKwMs",
                    "https://d1774jszgerdmk.cloudfront.net/512/8xCw_ZUcxe_GmjAS2I633",
                    "https://d1774jszgerdmk.cloudfront.net/512/ahtwOa3CMqHD7j1deEyhc"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10181,
                "dongName": "잠원동"
            },
            {
                "seq": 51896165,
                "id": "687f1788a67d20015b6a48bc",
                "roomTypeName": "아파트",
                "randomLocation": {
                    "lat": 37.489687,
                    "lng": 127.031051
                },
                "complexName": "에피소드강남262(민간임대,도시형)",
                "roomTitle": "실 120만. 60일 렌트프리. 전입신고 가능. 고층. 남향.",
                "roomDesc": "고층, 33.8m², 관리비 13만",
                "priceTypeName": "월세",
                "priceTitle": "1000/144",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/-wzRO4sm_MQoWT8xb7enk",
                    "https://d1774jszgerdmk.cloudfront.net/512/TkRdvKOtQYq-qgL-E1XcI",
                    "https://d1774jszgerdmk.cloudfront.net/512/ecNf0FzlIEA6Pi4AK41gt",
                    "https://d1774jszgerdmk.cloudfront.net/512/OQ02VgtifDUzt8B2ma0Hc",
                    "https://d1774jszgerdmk.cloudfront.net/512/DFsmWzDiWoeuEcZ9To--t"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10194,
                "dongName": "서초동"
            },
            {
                "seq": 51897481,
                "id": "687f219d59754426d172947e",
                "roomTypeName": "오피스텔",
                "randomLocation": {
                    "lat": 37.489948,
                    "lng": 127.02988
                },
                "complexName": "에피소드서초393",
                "roomTitle": "강아지OK. 실 128만. 60일 월세 무료. 전입 가능",
                "roomDesc": "고층, 29.82m², 관리비 17만",
                "priceTypeName": "월세",
                "priceTitle": "1000/154",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/dojwTDIp05SWpvnyrtwuw",
                    "https://d1774jszgerdmk.cloudfront.net/512/9CHzGun3PBnUJfT8H9gc5",
                    "https://d1774jszgerdmk.cloudfront.net/512/8HwpV5Ng0ZYQ9qENDuwWF",
                    "https://d1774jszgerdmk.cloudfront.net/512/cTxxHqqTGKcSoJFCj43c1",
                    "https://d1774jszgerdmk.cloudfront.net/512/Ihx-mxZ8W4CpeBM0ql8VN"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10194,
                "dongName": "서초동"
            },
            {
                "seq": 51857003,
                "id": "687d4d5fb45a5f3b34d3f070",
                "roomTypeName": "오피스텔",
                "randomLocation": {
                    "lat": 37.487597,
                    "lng": 127.014523
                },
                "complexName": "서초프라비다",
                "roomTitle": "남부터미널역 초역세권 깔끔한 저가형 오피스텔",
                "roomDesc": "11층, 14.47m², 관리비 9만",
                "priceTypeName": "월세",
                "priceTitle": "1000/77",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/-AreF8k8bwCtm1NpXSZW-",
                    "https://d1774jszgerdmk.cloudfront.net/512/2ZTDaS6I2sX18xkmxhQ7M",
                    "https://d1774jszgerdmk.cloudfront.net/512/shFrykmzAWObxfq3tOAL_",
                    "https://d1774jszgerdmk.cloudfront.net/512/EAhN5H7GJON7medwDmJrh",
                    "https://d1774jszgerdmk.cloudfront.net/512/aMK4KXWIuyzDzsFZzI-nH"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10194,
                "dongName": "서초동"
            },
            {
                "seq": 51764596,
                "id": "6875b2aed9ed0815ffaafd13",
                "roomTypeName": "원룸",
                "randomLocation": {
                    "lat": 37.4865523143088,
                    "lng": 126.977417977965
                },
                "complexName": null,
                "roomTitle": "깔끔한 화이트톤 양창 인테리어 초역세권 위치까지 빠른 입주 가능",
                "roomDesc": "2층, 19.83m², 관리비 8만",
                "priceTypeName": "월세",
                "priceTitle": "500/40",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/xwMVpx0gfxW6SoigCn42C",
                    "https://d1774jszgerdmk.cloudfront.net/512/AGHEjlVSe5SIIXRDRZu6H",
                    "https://d1774jszgerdmk.cloudfront.net/512/drN8_in36xcvE9P016JFV",
                    "https://d1774jszgerdmk.cloudfront.net/512/MauHgCq10-UjKldhxsXsV",
                    "https://d1774jszgerdmk.cloudfront.net/512/LLR93q81upOMyhSUoOxtj"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10148,
                "dongName": "사당동"
            },
            {
                "seq": 51988022,
                "id": "6886d4a008a61c1be7cf10aa",
                "roomTypeName": "투룸 • 단기",
                "randomLocation": {
                    "lat": 37.5071040491043,
                    "lng": 127.028953325379
                },
                "complexName": null,
                "roomTitle": "쌍둥이 2룸 각방 셋팅",
                "roomDesc": "3층, 42.97m², 관리비 없음",
                "priceTypeName": "월세",
                "priceTitle": "120/120",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/O8V8TWC8J8NqaoFTOfGjR",
                    "https://d1774jszgerdmk.cloudfront.net/512/s7HoOs6Bqsc0AudaDpkf8",
                    "https://d1774jszgerdmk.cloudfront.net/512/NVPu2N7ZBg2_LmfIRzz3p",
                    "https://d1774jszgerdmk.cloudfront.net/512/RQjUsYh8Jjoks3sD3cUSQ",
                    "https://d1774jszgerdmk.cloudfront.net/512/sSF3D_Sk082tL_EjpocEN"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10133,
                "dongName": "논현동"
            },
            {
                "seq": 51898879,
                "id": "687f2c77c8a7134b0d6c2df7",
                "roomTypeName": "원룸",
                "randomLocation": {
                    "lat": 37.5110360895695,
                    "lng": 127.017447761919
                },
                "complexName": null,
                "roomTitle": "논현역 가깝고 조용한 동네 예쁜 원룸",
                "roomDesc": "2층, 19.83m², 관리비 10만",
                "priceTypeName": "월세",
                "priceTitle": "1000/65",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/7dbbde0b-9082-457d-b445-2216e94f2d07",
                    "https://d1774jszgerdmk.cloudfront.net/512/dd101b39-e131-42c3-81e1-601dd2a85ba3",
                    "https://d1774jszgerdmk.cloudfront.net/512/84b8d82c-ec84-4a56-a771-5a17b3fadce4",
                    "https://d1774jszgerdmk.cloudfront.net/512/b5c4aabd-d069-4483-9887-e2b6a5ea6bbc",
                    "https://d1774jszgerdmk.cloudfront.net/512/56a87f65-a9f5-4b70-89f0-3cde371319ce"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10181,
                "dongName": "잠원동"
            },
            {
                "seq": 51964701,
                "id": "688395c489449302dd7a9027",
                "roomTypeName": "오피스텔",
                "randomLocation": {
                    "lat": 37.505553,
                    "lng": 127.027176
                },
                "complexName": "리체힐신논현",
                "roomTitle": "실매물o, 전입가능, 스타일러옵션, ACE Pick, Eng ok",
                "roomDesc": "12층, 22.43m², 관리비 20만",
                "priceTypeName": "월세",
                "priceTitle": "5500/109",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/QpR9YNwoC7uOA_cD__Fui",
                    "https://d1774jszgerdmk.cloudfront.net/512/Sthkck6PGj8Ve8IDy3sb-",
                    "https://d1774jszgerdmk.cloudfront.net/512/YLzZgVJCGvV-J07wgG7SO",
                    "https://d1774jszgerdmk.cloudfront.net/512/IN76ahjCYgg9lTAZyMuEC",
                    "https://d1774jszgerdmk.cloudfront.net/512/H687EzLFBGnj3ZiAbkSey"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10133,
                "dongName": "논현동"
            },
            {
                "seq": 51575430,
                "id": "686767d61adbe83d8a2baff3",
                "roomTypeName": "원룸",
                "randomLocation": {
                    "lat": 37.4963511342334,
                    "lng": 127.030712802642
                },
                "complexName": null,
                "roomTitle": "강남역 초역세권  깔끔한 풀옵션 원룸",
                "roomDesc": "5층, 19.83m², 관리비 7만",
                "priceTypeName": "월세",
                "priceTitle": "1000/63",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/vcwfPbJ2brJxzmsL-Sh6D",
                    "https://d1774jszgerdmk.cloudfront.net/512/pIQAuceEUJQlcW2wPENJw",
                    "https://d1774jszgerdmk.cloudfront.net/512/1QlPWv8BH5svjBhO9iase",
                    "https://d1774jszgerdmk.cloudfront.net/512/8W1FVlh_wwPv_txYsYojo",
                    "https://d1774jszgerdmk.cloudfront.net/512/2bLX66yTUun7pPMS_SBx_"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10063,
                "dongName": "역삼동"
            },
            {
                "seq": 52032179,
                "id": "6889852eb0c08372548b3f23",
                "roomTypeName": "투룸",
                "randomLocation": {
                    "lat": 37.4881162058933,
                    "lng": 126.989571148173
                },
                "complexName": null,
                "roomTitle": "내방역 역세권 2룸1거실",
                "roomDesc": "2층, 40.49m², 관리비 9.9만",
                "priceTypeName": "월세",
                "priceTitle": "5000/100",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/sqogpVqRoC62P0zfa452C",
                    "https://d1774jszgerdmk.cloudfront.net/512/7vFSZPFbsSYtFT0ubeEyq",
                    "https://d1774jszgerdmk.cloudfront.net/512/WYSnhw7FZw4fwKJTYSJWR",
                    "https://d1774jszgerdmk.cloudfront.net/512/6EO6Yd_tdcTuz6SDMRfEJ",
                    "https://d1774jszgerdmk.cloudfront.net/512/dEtqX42fAt1ayCFmF9SZn"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10295,
                "dongName": "방배동"
            },
            {
                "seq": 51978176,
                "id": "6884959b6f818966f3ecc51f",
                "roomTypeName": "원룸",
                "randomLocation": {
                    "lat": 37.4868165528655,
                    "lng": 126.976794219688
                },
                "complexName": null,
                "roomTitle": "분리형 신축급 이수역 초역세권 보증금조정 OK",
                "roomDesc": "2층, 19.83m², 관리비 8만",
                "priceTypeName": "월세",
                "priceTitle": "1000/28",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/oft5RLe2Sm-XgQm7Ez14a",
                    "https://d1774jszgerdmk.cloudfront.net/512/xYfja9jhNdLYvD2i14cM8",
                    "https://d1774jszgerdmk.cloudfront.net/512/4YwSGdehvc9s8h-u4we3y",
                    "https://d1774jszgerdmk.cloudfront.net/512/jIc8yc8JRn9TVEmqKtMsR",
                    "https://d1774jszgerdmk.cloudfront.net/512/ACbKhoEGcb6QKqGkZ-HeW"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10148,
                "dongName": "사당동"
            },
            {
                "seq": 52007268,
                "id": "688775879205ae48b49a7eea",
                "roomTypeName": "원룸 • 단기",
                "randomLocation": {
                    "lat": 37.5058973019089,
                    "lng": 127.019791398529
                },
                "complexName": null,
                "roomTitle": "떳다. 가성비 최고 신축급 컨디션나오는 인기만점 원룸.",
                "roomDesc": "중층, 20m², 관리비 7만",
                "priceTypeName": "월세",
                "priceTitle": "60/60",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/V2ba3mdOYIG9M-Gt9cMkx",
                    "https://d1774jszgerdmk.cloudfront.net/512/MCdF3Xk7ka7xukOwTSZVS",
                    "https://d1774jszgerdmk.cloudfront.net/512/g4diOwevEsqlNzAJAEwaL",
                    "https://d1774jszgerdmk.cloudfront.net/512/cfAjMdoyXLeyCInM2ONER",
                    "https://d1774jszgerdmk.cloudfront.net/512/m3OQJ3dSYLDYkRVbqHAaJ"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10172,
                "dongName": "반포동"
            },
            {
                "seq": 51898906,
                "id": "687f2ca8c81af8638fdb175a",
                "roomTypeName": "원룸",
                "randomLocation": {
                    "lat": 37.5059637188035,
                    "lng": 127.020839416796
                },
                "complexName": null,
                "roomTitle": "신논현 논현역 인근 준신축 원룸 대출가능",
                "roomDesc": "4층, 23.1m², 관리비 10만",
                "priceTypeName": "전세",
                "priceTitle": "1억8000",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/ID_mBt9IOqoedqGiFgjYH",
                    "https://d1774jszgerdmk.cloudfront.net/512/1PkFoP5wW88CNFD3L3PDf",
                    "https://d1774jszgerdmk.cloudfront.net/512/dPsGOIDinutBHg48Pl2NX",
                    "https://d1774jszgerdmk.cloudfront.net/512/zKtnmAYC0Qdn31L5C6Qfq",
                    "https://d1774jszgerdmk.cloudfront.net/512/J2xuzr-0oi17C5DspeQ7M"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10172,
                "dongName": "반포동"
            },
            {
                "seq": 51764591,
                "id": "6875b2acf2c62216d1eb7ea1",
                "roomTypeName": "원룸",
                "randomLocation": {
                    "lat": 37.4855544780552,
                    "lng": 126.979620826555
                },
                "complexName": null,
                "roomTitle": "이수역 코앞거리, 신축급 화이트톤, 엘베o",
                "roomDesc": "저층, 19.83m², 관리비 8만",
                "priceTypeName": "월세",
                "priceTitle": "500/40",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/BtokccI8Y_wZMW9vF6DIF",
                    "https://d1774jszgerdmk.cloudfront.net/512/swwJip6TBirZwNVgUm4e1",
                    "https://d1774jszgerdmk.cloudfront.net/512/28CH7QknggMLeaeWsbWHI"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10148,
                "dongName": "사당동"
            },
            {
                "seq": 51999397,
                "id": "68870d256e364a3b9261883f",
                "roomTypeName": "원룸",
                "randomLocation": {
                    "lat": 37.5056297461847,
                    "lng": 127.018910235215
                },
                "complexName": null,
                "roomTitle": "리모델링 + 넓은 원룸 + 베란다 + 신논현역/논현역 도보",
                "roomDesc": "저층, 26.44m², 관리비 7만",
                "priceTypeName": "월세",
                "priceTitle": "1000/70",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/b14216f3-a530-4612-8f48-f185fd71be24",
                    "https://d1774jszgerdmk.cloudfront.net/512/c8f687ae-727a-465f-8d4c-9c1c7d427106",
                    "https://d1774jszgerdmk.cloudfront.net/512/7d8268f2-08c3-456d-96b3-9d4a7523b082",
                    "https://d1774jszgerdmk.cloudfront.net/512/c72b096f-5850-43ff-8ff5-bc45daf5d04f",
                    "https://d1774jszgerdmk.cloudfront.net/512/589606ef-f1c1-42ff-9fda-ef7c03e98efd"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10172,
                "dongName": "반포동"
            },
            {
                "seq": 51976209,
                "id": "68847a4ac5f6000fec5a4775",
                "roomTypeName": "원룸 • 단기",
                "randomLocation": {
                    "lat": 37.5072446558752,
                    "lng": 127.027358589051
                },
                "complexName": null,
                "roomTitle": "o0월세할인ㅡ최고0o    전입신고 가능. 수납 굿",
                "roomDesc": "4층, 33.05m², 관리비 8만",
                "priceTypeName": "월세",
                "priceTitle": "80/80",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/MUjh-u0oDkzpg-GecmpMr",
                    "https://d1774jszgerdmk.cloudfront.net/512/k2hE3JZOJVo4EjT_tipsb",
                    "https://d1774jszgerdmk.cloudfront.net/512/3HmQeUyKRz8V-38qCj-7P",
                    "https://d1774jszgerdmk.cloudfront.net/512/MLWKyn_acOD8zMH7mRZmb",
                    "https://d1774jszgerdmk.cloudfront.net/512/7SVctbZkXCfpgZFQT9e46"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10133,
                "dongName": "논현동"
            },
            {
                "seq": 51951262,
                "id": "6882ec8c4c25643d2c99f526",
                "roomTypeName": "원룸",
                "randomLocation": {
                    "lat": 37.4870473142369,
                    "lng": 126.976328850116
                },
                "complexName": null,
                "roomTitle": "직접 찍어온 실매물 이수 초역세권 눈부신 양창채광 신축급",
                "roomDesc": "3층, 19.83m², 관리비 9만",
                "priceTypeName": "월세",
                "priceTitle": "500/47",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/SK8ETL6WuazMYp7U0Nbqg",
                    "https://d1774jszgerdmk.cloudfront.net/512/o3U33ChMftejgvtaNlkTE",
                    "https://d1774jszgerdmk.cloudfront.net/512/BOhTkFhPkhyPgedNkdVv0",
                    "https://d1774jszgerdmk.cloudfront.net/512/ueQ5Qyh56rrAQteziyxru",
                    "https://d1774jszgerdmk.cloudfront.net/512/019_l_LC-Ov_fOdPr8GFw"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10148,
                "dongName": "사당동"
            },
            {
                "seq": 51731162,
                "id": "68738da6279cf0611f043845",
                "roomTypeName": "투룸 • 단기",
                "randomLocation": {
                    "lat": 37.5095148524883,
                    "lng": 127.024480329346
                },
                "complexName": null,
                "roomTitle": "o월세 가드결제가능o 강남 거실이 넓은 논현동 투룸",
                "roomDesc": "저층, 42.97m², 관리비 10만",
                "priceTypeName": "월세",
                "priceTitle": "80/80",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/665bmlMHyqUGR_kPgjUPZ",
                    "https://d1774jszgerdmk.cloudfront.net/512/kdiQZJzGMgWFRL-nVsSut",
                    "https://d1774jszgerdmk.cloudfront.net/512/2zjfP4D4KtSFTCjDbzXnI",
                    "https://d1774jszgerdmk.cloudfront.net/512/1VL9kmDQb1UyKizlM0_F-",
                    "https://d1774jszgerdmk.cloudfront.net/512/1GsZ8krbouac4CkPzloGV"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10133,
                "dongName": "논현동"
            },
            {
                "seq": 51880957,
                "id": "687df2f1f7db4f3217684f65",
                "roomTypeName": "오피스텔",
                "randomLocation": {
                    "lat": 37.487597,
                    "lng": 127.014523
                },
                "complexName": "서초프라비다",
                "roomTitle": "실가격.교대최저가.전입가능",
                "roomDesc": "3층, 14.47m², 관리비 9만",
                "priceTypeName": "월세",
                "priceTitle": "1000/73",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/Z-c94_e_jCVd6PBzRjlP_",
                    "https://d1774jszgerdmk.cloudfront.net/512/WhBkcOw_b80KQ_7s_75so",
                    "https://d1774jszgerdmk.cloudfront.net/512/QKZZt5D5tl0bNX609Qk44",
                    "https://d1774jszgerdmk.cloudfront.net/512/oEIZkj7Ok8vEPw0ryySau",
                    "https://d1774jszgerdmk.cloudfront.net/512/Vw4uKtEsDL4pox-7d-0Ig"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10194,
                "dongName": "서초동"
            },
            {
                "seq": 51898918,
                "id": "687f2cb2544ec34b2d25c7f8",
                "roomTypeName": "원룸",
                "randomLocation": {
                    "lat": 37.4946830131755,
                    "lng": 127.030809760696
                },
                "complexName": null,
                "roomTitle": "강남역 바로 앞 / 신축급 컨디션 / 수납공간 완벽",
                "roomDesc": "5층, 15.91m², 관리비 17만",
                "priceTypeName": "월세",
                "priceTitle": "1000/75",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/_GjCJJXEmZs8TPvcE-MiA",
                    "https://d1774jszgerdmk.cloudfront.net/512/k7pjafpwDKHnDXsFNcj1R",
                    "https://d1774jszgerdmk.cloudfront.net/512/S4Y1OyAQ1pd4WMljM1Gxb",
                    "https://d1774jszgerdmk.cloudfront.net/512/F647qVNIR0cIOsgChkV0c",
                    "https://d1774jszgerdmk.cloudfront.net/512/fZd20YzByG_poA8CHl_Jj"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10063,
                "dongName": "역삼동"
            },
            {
                "seq": 51889945,
                "id": "687eefd6ef4f003fbfbf99b3",
                "roomTypeName": "투룸",
                "randomLocation": {
                    "lat": 37.4864005171705,
                    "lng": 127.00570458046
                },
                "complexName": null,
                "roomTitle": "HUG대출,보증보험o 서초역 법조타운 신축 첫입주 화이트톤 투룸 병렬주차",
                "roomDesc": "6층, 27.1m², 관리비 확인 불가",
                "priceTypeName": "전세",
                "priceTitle": "4억1000",
                "imgUrlList": [
                    "https://d1774jszgerdmk.cloudfront.net/512/OYI5NJDTpdh0vIJlkUYkB",
                    "https://d1774jszgerdmk.cloudfront.net/512/-w98pubCXic_ky62cr4pG",
                    "https://d1774jszgerdmk.cloudfront.net/512/oAh8OfL0sa8XfiqzbzCSs",
                    "https://d1774jszgerdmk.cloudfront.net/512/cFAA5Bl5E_DR-8Ai-WluM",
                    "https://d1774jszgerdmk.cloudfront.net/512/VdR2obfvCFgbftxKVnvX5"
                ],
                "isExtendUI": true,
                "isFavorite": false,
                "isPano": false,
                "isQuick": true,
                "isDirect": false,
                "isOwner": false,
                "isNaverVerify": false,
                "formatNaverVerifyDate": null,
                "isIconFocus": false,
                "iconFocusType": null,
                "gid": 10194,
                "dongName": "서초동"
            }
        ],
        "premiumList": [],
        "region": null,
        "total": 544,
        "limit": 24,
        "hasMore": true,
        "page": 1
    },
    "responseTime": "2025-07-30 19:03:49"
}


const makeRoom = (x) => 